/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpit305project;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Abdulaziz
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        diabetesButtonGroup = new javax.swing.ButtonGroup();
        obesityButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        diabetesLabel = new javax.swing.JLabel();
        obesityLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        obesityNRadioButton = new javax.swing.JRadioButton();
        diabetesNRadioButton = new javax.swing.JRadioButton();
        diabetesYRadioButton = new javax.swing.JRadioButton();
        obesityYRadioButton = new javax.swing.JRadioButton();
        registerButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        ssnTextField = new javax.swing.JTextField();
        ssnLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        backButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nameLabel.setText("Name:");

        ageLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ageLabel.setText("Age:");

        diabetesLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        diabetesLabel.setText("Diabetes:");

        obesityLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        obesityLabel.setText("Obesity:");

        obesityButtonGroup.add(obesityNRadioButton);
        obesityNRadioButton.setSelected(true);
        obesityNRadioButton.setText("No");

        diabetesButtonGroup.add(diabetesNRadioButton);
        diabetesNRadioButton.setSelected(true);
        diabetesNRadioButton.setText("No");

        diabetesButtonGroup.add(diabetesYRadioButton);
        diabetesYRadioButton.setText("Yes");

        obesityButtonGroup.add(obesityYRadioButton);
        obesityYRadioButton.setText("Yes");

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passwordLabel.setText("Password:");

        ssnLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ssnLabel.setText("SSN:");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ssnLabel)
                                    .addComponent(ageLabel))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(passwordLabel)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(ageTextField)
                            .addComponent(ssnTextField)
                            .addComponent(nameTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diabetesLabel)
                            .addComponent(obesityLabel))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(diabetesYRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(diabetesNRadioButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(obesityYRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(obesityNRadioButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(registerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnLabel)
                    .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diabetesLabel)
                    .addComponent(diabetesYRadioButton)
                    .addComponent(diabetesNRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obesityNRadioButton)
                    .addComponent(obesityYRadioButton)
                    .addComponent(obesityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(backButton)
                    .addComponent(exitButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        try {
            // if null, inform the user
            // if information is repeated, check with the user
            String name = nameTextField.getText();
            checkDigit(name);
            String temp = ssnTextField.getText();
            int ssn = checkSSN(temp);// must check in database that SSN in not repeated, if it is inform the user an account exists with this SSN
            if(ssn == -1){
                showMessageDialog(null, "Wrong input! Your SSN should be 7 digits.");
            }
            int age = Integer.parseInt(ageTextField.getText());
            char[] pass = passwordField.getPassword();
            String password = checkPassword(pass);
            if(password.equalsIgnoreCase("try again")){
                showMessageDialog(null, "Wrong input! Please enter a password within (7 to 12) characters.");
            }
            boolean diabetes = false, obesity = false;
            if (diabetesYRadioButton.isSelected()) {
                diabetes = true;
            } else {
                diabetes = false;
            }
            if (obesityYRadioButton.isSelected()) {
                obesity = true;
            } else {
                obesity = false;
            }
            Appointee p = new Appointee(ssn, password, name, age, diabetes, obesity, false);
            ClientSide c = new ClientSide(p);
            System.out.println(c);
        } catch (isNumberException ee) {
            showMessageDialog(null, ee.getMessage());
        } catch (NumberFormatException e) {
            showMessageDialog(null, "Wrong input! Please enter the corresponding information.");
        } catch (NullPointerException n) {
            showMessageDialog(null, "Wrong input! Please enter the value.");
        }
    }                                              

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }                                          

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        System.exit(0);
    }                                          

    private void checkDigit(String name) {
        char temp;
        for (int i = 0; i < name.length(); i++) {
            temp = name.charAt(i);
            if (Character.isDigit(temp)) {
                throw new isNumberException("Wrong input! Please enter the corresponding information.");
            }
        }
    }

    private int checkSSN(String ssn) {
        int temp = -1;
        if (ssn.length() > 6 && ssn.length() <= 7) {
            temp = Integer.parseInt(ssn);
        }
        return temp;
    }

    private String checkPassword(char[] pass) {
        String temp = "";
        for (int i = 0; i < pass.length; i++) {
            temp += pass[i];
        }
        if (temp.length() > 6 && temp.length() <= 12) {
            return temp;
        }
        return "try again";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup diabetesButtonGroup;
    private javax.swing.JLabel diabetesLabel;
    private javax.swing.JRadioButton diabetesNRadioButton;
    private javax.swing.JRadioButton diabetesYRadioButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.ButtonGroup obesityButtonGroup;
    private javax.swing.JLabel obesityLabel;
    private javax.swing.JRadioButton obesityNRadioButton;
    private javax.swing.JRadioButton obesityYRadioButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JTextField ssnTextField;
    // End of variables declaration                   
}

class isNumberException extends NumberFormatException {

    public isNumberException(String s) {
        super(s);
    }
}
